---
- hosts: all
  serial: 1

  vars_files:
      - default_variables.yml
      - vault.yml

  pre_tasks:
      - name: Run sanity checks
        import_tasks: tasks/sanity.yml
        tags: ["always", "sanity"]

  tasks:
      - name: Update apt packages
        import_tasks: tasks/update.yml
        tags: ["update"]
      - name: Cloudflare IP Update
        import_tasks: tasks/cloudflare-ip.yml
        tags: ["cloudflare_ip"]
      - name: Install Traefik
        import_tasks: tasks/install-traefik.yml
        tags: ["traefik"]
      - name: Install Crowdsec
        import_tasks: tasks/install-crowdsec.yml
        tags: ["crowdsec"]
      - name: Install Plausible Analytics
        import_tasks: tasks/install-plausible.yml
        tags: ["plausible"]

  handlers:
      - ansible.builtin.import_tasks: handlers/main.yml
