---
- name: install jq
  become: true
  ansible.builtin.apt:
      pkg: "{{ item }}"
      state: present
  loop:
      - jq

- name: "create {{ ansible_user_dir }}/{{ public_ip_tmp_dir }}"
  become: true
  ansible.builtin.file:
      path: "{{ ansible_user_dir }}/{{ public_ip_tmp_dir }}"
      state: directory
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: "0770"

- name: "create {{ ansible_user_dir }}/bin"
  become: true
  ansible.builtin.file:
      path: "{{ ansible_user_dir }}/bin"
      state: directory
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: "0770"

- name: copy shell script
  become: true
  ansible.builtin.template:
      src: cloudflare-ip-update.sh.j2
      dest: "{{ ansible_user_dir }}/bin/cloudflare-ip-update.sh"
      owner: "{{ ansible_user_uid }}"
      group: "{{ ansible_user_gid }}"
      mode: "0770"

- name: run the script
  become: true
  ansible.builtin.command:
      cmd: "{{ ansible_user_dir }}/bin/cloudflare-ip-update.sh"
  register: cloudflareIPUpdate
  changed_when: false
  failed_when: cloudflareIPUpdate.rc > 0

- name: "add shell script to {{ ansible_user_id }} cron"
  become: true
  ansible.builtin.cron:
      name: "Update IP on Cloudflare"
      minute: "15"
      hour: "0"
      job: "{{ ansible_user_dir }}/bin/cloudflare-ip-update.sh"
      state: present
      user: "{{ ansible_user_id }}"
