---
- name: Ensure group "docker" exists
  ansible.builtin.group:
      name: docker
      state: present

- name: "install required packages for Docker"
  become: true
  ansible.builtin.apt:
      pkg: "{{ item }}"
      state: present
  loop:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: Download Docker GPG key
  become: true
  ansible.builtin.apt_key:
      state: present
      url: "https://download.docker.com/linux/debian/gpg"

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
      repo: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present
      update_cache: true

- name: install docker packages
  become: true
  ansible.builtin.apt:
      pkg: "{{ item }}"
      state: present
  loop:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: "add {{ ansible_user_id }} to the docker group"
  become: true
  ansible.builtin.user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: true
