---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
      pkg: "{{ item }}"
      state: present
  loop:
      - apt-transport-https
      - gnupg

- name: Add an apt signing key
  become: true
  ansible.builtin.apt_key:
      url: "https://packagecloud.io/crowdsec/crowdsec/gpgkey"

- name: Add apt repo
  become: true
  ansible.builtin.apt_repository:
      repo: "deb https://packagecloud.io/crowdsec/crowdsec/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release | lower }} main"
      update_cache: true

- name: Install package
  become: true
  ansible.builtin.apt:
      pkg: crowdsec
      state: present
  notify: restart_crowdsec

- name: install bouncers
  become: true
  ansible.builtin.apt:
      pkg: "{{ item }}"
      state: present
  loop: "{{ crowdsec_bouncers }}"
  notify: restart_crowdsec

- name: list installed bouncers
  become: true
  ansible.builtin.command:
      cmd: cscli bouncers list
  register: installed_bouncers
  changed_when: false

- name: list installed collections
  become: true
  ansible.builtin.command:
      cmd: cscli collections list
  register: installed_collections
  changed_when: false

- name: "install collections"
  become: true
  ansible.builtin.command:
      cmd: "cscli collections install {{ item }}"
  notify: restart_crowdsec
  when: item not in installed_collections.stdout
  changed_when: item not in installed_collections.stdout
  loop: "{{ crowdsec_collections }}"

- name: list installed collections
  become: true
  ansible.builtin.command:
      cmd: cscli collections list
  register: installed_collections
  changed_when: false

- name: Configure traefik collection
  become: true
  ansible.builtin.blockinfile:
      path: /etc/crowdsec/acquis.yaml
      state: present
      marker: "# {mark} traefik block"
      block: |
          # Configuration for traefik collection
          # https://hub.crowdsec.net/author/crowdsecurity/collections/traefik
          filenames:
            - /var/log/traefik/*.log
          labels:
            type: traefik
          ---
  notify: restart_crowdsec
  when: "'traefik' in installed_collections.stdout"

- name: Configure authelia collection
  become: true
  ansible.builtin.blockinfile:
      path: /etc/crowdsec/acquis.yaml
      state: present
      marker: "# {mark} authelia block"
      block: |
          # https://hub.crowdsec.net/author/LePresidente/collections/authelia
          filenames:
            - /var/log/authelia/*.log
          labels:
            type: authelia
          ---
  notify: restart_crowdsec
  when: "'authelia' in installed_collections.stdout"

- name: Configure nginx collection
  become: true
  ansible.builtin.blockinfile:
      path: /etc/crowdsec/acquis.yaml
      state: present
      marker: "# {mark} nginx block"
      block: |
          # https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
          filenames:
            - /var/log/nginx/*.log
          labels:
            type: nginx
          ---
  notify: restart_crowdsec
  when: "'nginx' in installed_collections.stdout"

- name: "Configure Cloudflare bouncer"
  when: "'crowdsec-cloudflare-bouncer' in installed_bouncers.stdout or 'crowdsec-cloudflare-bouncer' in crowdsec_bouncers"
  block:
      - name: "Clean existing cloudflare bouncer components"
        become: true
        ansible.builtin.command:
            cmd: "sudo crowdsec-cloudflare-bouncer -d"
        ignore_errors: true
        changed_when: false

      - name: "Configure cloudflare bouncer"
        become: true
        ansible.builtin.command:
            cmd: "crowdsec-cloudflare-bouncer -g {{ crowdsec_cloudflare_bouncer_token }} -o /etc/crowdsec/bouncers/crowdsec-cloudflare-bouncer.yaml"
        changed_when: false

      - name: "Set up IP lists and firewall rules at cloudflare"
        become: true
        ansible.builtin.command:
            cmd: "sudo crowdsec-cloudflare-bouncer -s"
        changed_when: false

      - name: "Start Cloudflare Bouncer"
        become: true
        ansible.builtin.systemd:
            state: restarted
            name: crowdsec-cloudflare-bouncer

- name: "Template Email Notification File"
  become: true
  ansible.builtin.template:
      src: "crowdsec-email.yaml.j2"
      dest: "/etc/crowdsec/notifications/email.yaml"
      mode: 0644
  notify: restart_crowdsec

- name: "Enable email notifications"
  become: true
  ansible.builtin.blockinfile:
      path: /etc/crowdsec/profiles.yaml
      state: present
      block: |
          notifications:
            - email_default
  notify: restart_crowdsec

- name: "Add crowdsec update to cron"
  become: true
  ansible.builtin.cron:
      name: "Update crowdsec"
      job: cscli hub update && cscli hub upgrade
      minute: "15"
      hour: "0"
      state: present
