---
- name: update APT package cache
  become: true
  ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600

- name: "upgrade APT to the latest packages (this may take a while)"
  become: true
  ansible.builtin.apt:
      upgrade: safe
