---
- name: Restart Crowdsec
  become: true
  ansible.builtin.service:
      name: crowdsec
      state: restarted
      enabled: true
  listen: restart_crowdsec

- name: "Is reverse proxy running running"
  become: true
  ansible.builtin.shell:
      cmd: |
          set -o pipefail
          docker ps --format '{{ '{{' }}.Names{{ '}}' }}' | grep -w traefik
      executable: /bin/bash
  register: docker_running
  ignore_errors: true
  changed_when: false
  listen: restart_proxy

- name: "stop reverse proxy"
  become: true
  ansible.builtin.command:
      cmd: "docker compose -f {{ docker_dir }}/reverse_proxy.yml down"
  when: docker_running.rc == 0
  changed_when: false
  listen: restart_proxy
  ignore_errors: true

- name: "Start reverse proxy"
  become: true
  ansible.builtin.command:
      cmd: "docker compose -f {{ docker_dir }}/reverse_proxy.yml up -d"
  changed_when: false
  listen: restart_proxy

- name: "Is plausible running"
  become: true
  ansible.builtin.shell:
      cmd: |
          set -o pipefail
          docker ps --format '{{ '{{' }}.Names{{ '}}' }}' | grep -w plausible
      executable: /bin/bash
  register: docker_running
  ignore_errors: true
  changed_when: false
  listen: restart_plausible

- name: "stop plausible"
  become: true
  ansible.builtin.command:
      cmd: "docker compose -f {{ docker_dir }}/plausible/docker-compose.yml down"
  when: docker_running.rc == 0
  changed_when: false
  listen: restart_plausible
  ignore_errors: true

- name: "Start plausible"
  become: true
  ansible.builtin.command:
      cmd: "docker compose -f {{ docker_dir }}/plausible/docker-compose.yml up -d"
  changed_when: false
  listen: restart_plausible
