---
- name: Restart Crowdsec
  become: true
  ansible.builtin.service:
      name: crowdsec
      state: restarted
      enabled: true
  listen: restart_crowdsec

- name: "Is traefik running"
  ansible.builtin.shell:
      cmd: |
          set -o pipefail
          docker ps --format '{{ '{{' }}.Names{{ '}}' }}' | grep -w traefik
      executable: /bin/bash
  register: docker_running
  ignore_errors: true
  changed_when: false
  listen: restart_traefik

- name: "stop traefik"
  ansible.builtin.command:
      cmd: "docker compose -f {{ primary_user_home_dir }}/services/traefik/traefik.yml down"
  when: docker_running.rc == 0
  changed_when: false
  listen: restart_traefik

- name: "Start traefik"
  ansible.builtin.command:
      cmd: "docker compose -f {{ primary_user_home_dir }}/services/traefik/traefik.yml up -d"
  changed_when: false
  listen: restart_traefik

- name: "Is plausible running"
  ansible.builtin.shell:
      cmd: |
          set -o pipefail
          docker ps --format '{{ '{{' }}.Names{{ '}}' }}' | grep -w plausible
      executable: /bin/bash
  register: docker_running
  ignore_errors: true
  changed_when: false
  listen: restart_plausible

- name: "stop plausible"
  ansible.builtin.command:
      cmd: "docker compose -f {{ primary_user_home_dir }}/services/plausible/docker-compose.yml down"
  when: docker_running.rc == 0
  changed_when: false
  listen: restart_plausible

- name: "Start plausible"
  ansible.builtin.command:
      cmd: "docker compose -f {{ primary_user_home_dir }}/services/plausible/docker-compose.yml up -d"
  changed_when: false
  listen: restart_plausible
